//Generated by helper.py
#pragma once
#include <cstdint>
#include <iostream>
#include <vector>
#define print(x) std::cout<< x;
#define NL std::cout << "\n";

typedef char byte;

typedef struct Stack
{
    void* values;
    
    uint32_t pointer = 0;
} Stack;

inline Value* PopStack(Stack& opStack)
{
    Value* val = &(((Value*)opStack.values)[opStack.pointer]);
    opStack.pointer--;

    return val;
} 

inline void PushStack(Value val, Stack& opStack)
{
    opStack.pointer++;
    ((Value*)opStack.values)[opStack.pointer] = val;
}
typedef union Value
{
	uint32_t intVal;
	float floatVal;
	bool boolVal;
} Value;inline Value FetchInstruction_int(void* startAdr,uint32_t* current)
{
    //Expecting current to be at the first byte
    *current += sizeof(uint32_t);

    Value val;
    val.intVal = *(uint32_t*)startAdr;
    return val;
}inline Value FetchInstruction_float(void* startAdr,uint32_t* current)
{
    //Expecting current to be at the first byte
    *current += sizeof(float);

    Value val;
    val.floatVal = *(float*)startAdr;
    return val;
}inline Value FetchInstruction_bool(void* startAdr,uint32_t* current)
{
    //Expecting current to be at the first byte
    *current += sizeof(bool);

    Value val;
    val.boolVal = *(bool*)startAdr;
    return val;
}
inline void Add_int(Stack& opStack)
{
	Value newVal;
	newVal.intVal = PopStack(opStack)->intVal+PopStack(opStack)->intVal; 
	PushStack(newVal,opStack);
}
inline void Add_float(Stack& opStack)
{
	Value newVal;
	newVal.floatVal = PopStack(opStack)->floatVal+PopStack(opStack)->floatVal; 
	PushStack(newVal,opStack);
}

inline void Add_int(Stack& opStack)
{
	Value newVal;
	newVal.intVal = PopStack(opStack)->intVal+PopStack(opStack)->intVal; 
	PushStack(newVal,opStack);
}
inline void Add_float(Stack& opStack)
{
	Value newVal;
	newVal.floatVal = PopStack(opStack)->floatVal+PopStack(opStack)->floatVal; 
	PushStack(newVal,opStack);
}
inline void Sub_int(Stack& opStack)
{
	Value newVal;
	newVal.intVal = PopStack(opStack)->intVal-PopStack(opStack)->intVal; 
	PushStack(newVal,opStack);
}
inline void Sub_float(Stack& opStack)
{
	Value newVal;
	newVal.floatVal = PopStack(opStack)->floatVal-PopStack(opStack)->floatVal; 
	PushStack(newVal,opStack);
}

inline void Add_int(Stack& opStack)
{
	Value newVal;
	newVal.intVal = PopStack(opStack)->intVal+PopStack(opStack)->intVal; 
	PushStack(newVal,opStack);
}
inline void Add_float(Stack& opStack)
{
	Value newVal;
	newVal.floatVal = PopStack(opStack)->floatVal+PopStack(opStack)->floatVal; 
	PushStack(newVal,opStack);
}
inline void Sub_int(Stack& opStack)
{
	Value newVal;
	newVal.intVal = PopStack(opStack)->intVal-PopStack(opStack)->intVal; 
	PushStack(newVal,opStack);
}
inline void Sub_float(Stack& opStack)
{
	Value newVal;
	newVal.floatVal = PopStack(opStack)->floatVal-PopStack(opStack)->floatVal; 
	PushStack(newVal,opStack);
}
inline void Mul_int(Stack& opStack)
{
	Value newVal;
	newVal.intVal = PopStack(opStack)->intVal*PopStack(opStack)->intVal; 
	PushStack(newVal,opStack);
}
inline void Mul_float(Stack& opStack)
{
	Value newVal;
	newVal.floatVal = PopStack(opStack)->floatVal*PopStack(opStack)->floatVal; 
	PushStack(newVal,opStack);
}

inline void Add_int(Stack& opStack)
{
	Value newVal;
	newVal.intVal = PopStack(opStack)->intVal+PopStack(opStack)->intVal; 
	PushStack(newVal,opStack);
}
inline void Add_float(Stack& opStack)
{
	Value newVal;
	newVal.floatVal = PopStack(opStack)->floatVal+PopStack(opStack)->floatVal; 
	PushStack(newVal,opStack);
}
inline void Sub_int(Stack& opStack)
{
	Value newVal;
	newVal.intVal = PopStack(opStack)->intVal-PopStack(opStack)->intVal; 
	PushStack(newVal,opStack);
}
inline void Sub_float(Stack& opStack)
{
	Value newVal;
	newVal.floatVal = PopStack(opStack)->floatVal-PopStack(opStack)->floatVal; 
	PushStack(newVal,opStack);
}
inline void Mul_int(Stack& opStack)
{
	Value newVal;
	newVal.intVal = PopStack(opStack)->intVal*PopStack(opStack)->intVal; 
	PushStack(newVal,opStack);
}
inline void Mul_float(Stack& opStack)
{
	Value newVal;
	newVal.floatVal = PopStack(opStack)->floatVal*PopStack(opStack)->floatVal; 
	PushStack(newVal,opStack);
}
inline void Div_int(Stack& opStack)
{
	Value newVal;
	newVal.intVal = PopStack(opStack)->intVal/PopStack(opStack)->intVal; 
	PushStack(newVal,opStack);
}
inline void Div_float(Stack& opStack)
{
	Value newVal;
	newVal.floatVal = PopStack(opStack)->floatVal/PopStack(opStack)->floatVal; 
	PushStack(newVal,opStack);
}

inline void CmpEq_int(Stack& opStack)
{
	Value val;
	if(PopStack(opStack)->intVal == PopStack(opStack)->intVal)
	{
		val.intVal = 1;
		PushStack(val,opStack);
	}
	else
	{
		val.intVal = 0;
		PushStack(val,opStack);
	}

}inline void CmpNEq_int(Stack& opStack)
{
	Value val;
	if(PopStack(opStack)->intVal != PopStack(opStack)->intVal)
	{
		val.intVal = 1;
		PushStack(val,opStack);
	}
	else
	{
		val.intVal = 0;
		PushStack(val,opStack);
	}

}inline void CmpL_int(Stack& opStack)
{
	Value val;
	if(PopStack(opStack)->intVal < PopStack(opStack)->intVal)
	{
		val.intVal = 1;
		PushStack(val,opStack);
	}
	else
	{
		val.intVal = 0;
		PushStack(val,opStack);
	}

}inline void CmpG_int(Stack& opStack)
{
	Value val;
	if(PopStack(opStack)->intVal > PopStack(opStack)->intVal)
	{
		val.intVal = 1;
		PushStack(val,opStack);
	}
	else
	{
		val.intVal = 0;
		PushStack(val,opStack);
	}

}inline void CmpLEq_int(Stack& opStack)
{
	Value val;
	if(PopStack(opStack)->intVal <= PopStack(opStack)->intVal)
	{
		val.intVal = 1;
		PushStack(val,opStack);
	}
	else
	{
		val.intVal = 0;
		PushStack(val,opStack);
	}

}inline void CmpGEq_int(Stack& opStack)
{
	Value val;
	if(PopStack(opStack)->intVal >= PopStack(opStack)->intVal)
	{
		val.intVal = 1;
		PushStack(val,opStack);
	}
	else
	{
		val.intVal = 0;
		PushStack(val,opStack);
	}

}inline void CmpEq_float(Stack& opStack)
{
	Value val;
	if(PopStack(opStack)->floatVal == PopStack(opStack)->floatVal)
	{
		val.intVal = 1;
		PushStack(val,opStack);
	}
	else
	{
		val.intVal = 0;
		PushStack(val,opStack);
	}

}inline void CmpNEq_float(Stack& opStack)
{
	Value val;
	if(PopStack(opStack)->floatVal != PopStack(opStack)->floatVal)
	{
		val.intVal = 1;
		PushStack(val,opStack);
	}
	else
	{
		val.intVal = 0;
		PushStack(val,opStack);
	}

}inline void CmpL_float(Stack& opStack)
{
	Value val;
	if(PopStack(opStack)->floatVal < PopStack(opStack)->floatVal)
	{
		val.intVal = 1;
		PushStack(val,opStack);
	}
	else
	{
		val.intVal = 0;
		PushStack(val,opStack);
	}

}inline void CmpG_float(Stack& opStack)
{
	Value val;
	if(PopStack(opStack)->floatVal > PopStack(opStack)->floatVal)
	{
		val.intVal = 1;
		PushStack(val,opStack);
	}
	else
	{
		val.intVal = 0;
		PushStack(val,opStack);
	}

}inline void CmpLEq_float(Stack& opStack)
{
	Value val;
	if(PopStack(opStack)->floatVal <= PopStack(opStack)->floatVal)
	{
		val.intVal = 1;
		PushStack(val,opStack);
	}
	else
	{
		val.intVal = 0;
		PushStack(val,opStack);
	}

}inline void CmpGEq_float(Stack& opStack)
{
	Value val;
	if(PopStack(opStack)->floatVal >= PopStack(opStack)->floatVal)
	{
		val.intVal = 1;
		PushStack(val,opStack);
	}
	else
	{
		val.intVal = 0;
		PushStack(val,opStack);
	}

}inline void CmpEq_bool(Stack& opStack)
{
	Value val;
	if(PopStack(opStack)->boolVal == PopStack(opStack)->boolVal)
	{
		val.intVal = 1;
		PushStack(val,opStack);
	}
	else
	{
		val.intVal = 0;
		PushStack(val,opStack);
	}

}inline void CmpNEq_bool(Stack& opStack)
{
	Value val;
	if(PopStack(opStack)->boolVal != PopStack(opStack)->boolVal)
	{
		val.intVal = 1;
		PushStack(val,opStack);
	}
	else
	{
		val.intVal = 0;
		PushStack(val,opStack);
	}

}inline void CmpL_bool(Stack& opStack)
{
	Value val;
	if(PopStack(opStack)->boolVal < PopStack(opStack)->boolVal)
	{
		val.intVal = 1;
		PushStack(val,opStack);
	}
	else
	{
		val.intVal = 0;
		PushStack(val,opStack);
	}

}inline void CmpG_bool(Stack& opStack)
{
	Value val;
	if(PopStack(opStack)->boolVal > PopStack(opStack)->boolVal)
	{
		val.intVal = 1;
		PushStack(val,opStack);
	}
	else
	{
		val.intVal = 0;
		PushStack(val,opStack);
	}

}inline void CmpLEq_bool(Stack& opStack)
{
	Value val;
	if(PopStack(opStack)->boolVal <= PopStack(opStack)->boolVal)
	{
		val.intVal = 1;
		PushStack(val,opStack);
	}
	else
	{
		val.intVal = 0;
		PushStack(val,opStack);
	}

}inline void CmpGEq_bool(Stack& opStack)
{
	Value val;
	if(PopStack(opStack)->boolVal >= PopStack(opStack)->boolVal)
	{
		val.intVal = 1;
		PushStack(val,opStack);
	}
	else
	{
		val.intVal = 0;
		PushStack(val,opStack);
	}

}inline void Define_int(Stack& memStack)
{
	memStack.pointer++;
	((Value*)memStack.values)[memStack.pointer] = Value();

}
inline void Define_float(Stack& memStack)
{
	memStack.pointer++;
	((Value*)memStack.values)[memStack.pointer] = Value();

}
inline void Define_bool(Stack& memStack)
{
	memStack.pointer++;
	((Value*)memStack.values)[memStack.pointer] = Value();

}

inline void Set_int(uint32_t* current, Stack& opStack, Stack& memStack, std::vector<byte>& bytecode)
{
	*current++;
	Value setAdr = FetchInstruction_int(&(bytecode[*current]),current);
	((Value*)memStack.values)[setAdr.intVal] = *PopStack(opStack);
}
inline void Load_int(uint32_t* current, Stack& opStack, Stack& memStack, std::vector<byte>& bytecode)
{
	*current++;
	Value getAdr = FetchInstruction_int(&(bytecode[*current]),current);
	PushStack(((Value*)memStack.values)[getAdr.intVal], opStack);
}inline void Load_float(uint32_t* current, Stack& opStack, Stack& memStack, std::vector<byte>& bytecode)
{
	*current++;
	Value getAdr = FetchInstruction_int(&(bytecode[*current]),current);
	PushStack(((Value*)memStack.values)[getAdr.intVal], opStack);
}inline void Load_bool(uint32_t* current, Stack& opStack, Stack& memStack, std::vector<byte>& bytecode)
{
	*current++;
	Value getAdr = FetchInstruction_int(&(bytecode[*current]),current);
	PushStack(((Value*)memStack.values)[getAdr.intVal], opStack);
}inline void Push_int(uint32_t* current, Stack& opStack, std::vector<byte>& bytecode)
{
	*current++;
	PushStack(FetchInstruction_int(&(bytecode[*current]),current),opStack);
	
}
inline void Push_float(uint32_t* current, Stack& opStack, std::vector<byte>& bytecode)
{
	*current++;
	PushStack(FetchInstruction_float(&(bytecode[*current]),current),opStack);
	
}
inline void Push_bool(uint32_t* current, Stack& opStack, std::vector<byte>& bytecode)
{
	*current++;
	PushStack(FetchInstruction_bool(&(bytecode[*current]),current),opStack);
	
}

inline void Not_bool(Stack& opStack)
{
	Value invVal = *PopStack(opStack);
	invVal.boolVal = !invVal.boolVal;
	PushStack(invVal,opStack);
}

inline void And_bool(Stack& opStack)
{
	Value invVal = *PopStack(opStack);
	invVal.boolVal = invVal.boolVal && PopStack(opStack)->boolVal;
	PushStack(invVal,opStack);
}

inline void Or_bool(Stack& opStack)
{
	Value invVal = *PopStack(opStack);
	invVal.boolVal = invVal.boolVal || PopStack(opStack)->boolVal;
	PushStack(invVal,opStack);
}

inline void Comp_int(Stack& opStack, byte* cmpFlag)
{
	int cmpVal = PopStack(opStack)->intVal;
	if(cmpVal < 0)
	{
		*cmpFlag = -1;
	}
	else if(cmpVal > 0)
	{
		*cmpFlag = 1;
	}
	else
	{
		*cmpFlag = 0;
	}
}

inline void Jmp_int(uint32_t* current, std::vector<byte> bytecode)
{
	//TODO: fix jmp targets in CodeGen.
	*current = ; 
}

inline void Call_int(Stack& opStack)
{
	Value val = *PopStack(opStack);
	print(val.intVal) NL
}



void RunVM(std::vector<byte>& bytecode) 
{
	Value opStack[256];

	Stack operationStack;

	operationStack.values = (void*)opStack;

	Value memStack[4096];

	Stack memoryStack;

	memoryStack.values = (void*)memStack;
	
	uint32_t current = -1;

	byte cmpFlag = 0;

    void *instructionLabels[27*3] = 
 {
&&_End_int,&&_End_float,&&_End_bool,
&&_Define_int,&&_Define_float,&&_Define_bool,
&&_Add_int,&&_Add_float,&&_Add_bool,
&&_Mul_int,&&_Mul_float,&&_Mul_bool,
&&_Sub_int,&&_Sub_float,&&_Sub_bool,
&&_Div_int,&&_Div_float,&&_Div_bool,
&&_Not_int,&&_Not_float,&&_Not_bool,
&&_And_int,&&_And_float,&&_And_bool,
&&_Or_int,&&_Or_float,&&_Or_bool,
&&_Set_int,&&_Set_float,&&_Set_bool,
&&_Call_int,&&_Call_float,&&_Call_bool,
&&_CallNative_int,&&_CallNative_float,&&_CallNative_bool,
&&_Comp_int,&&_Comp_float,&&_Comp_bool,
&&_CmpG_int,&&_CmpG_float,&&_CmpG_bool,
&&_CmpGEq_int,&&_CmpGEq_float,&&_CmpGEq_bool,
&&_CmpL_int,&&_CmpL_float,&&_CmpL_bool,
&&_CmpLEq_int,&&_CmpLEq_float,&&_CmpLEq_bool,
&&_CmpEq_int,&&_CmpEq_float,&&_CmpEq_bool,
&&_CmpNEq_int,&&_CmpNEq_float,&&_CmpNEq_bool,
&&_Push_int,&&_Push_float,&&_Push_bool,
&&_Load_int,&&_Load_float,&&_Load_bool,
&&_Jmp_int,&&_Jmp_float,&&_Jmp_bool,
&&_JmpTrue_int,&&_JmpTrue_float,&&_JmpTrue_bool,
&&_JmpFalse_int,&&_JmpFalse_float,&&_JmpFalse_bool
};
start:
	 current++;
goto *instructionLabels[bytecode[current]];_End_int:
goto start;

_End_float:
goto start;

_End_bool:
goto start;

_Define_int:
Define_int(memoryStack);
goto start;

_Define_float:
Define_float(memoryStack);
goto start;

_Define_bool:
Define_bool(memoryStack);
goto start;

_Add_int:
Add_int(operationStack);
goto start;

_Add_float:
Add_float(operationStack);
goto start;

_Add_bool:
goto start;

_Mul_int:
Mul_int(operationStack);
goto start;

_Mul_float:
Mul_float(operationStack);
goto start;

_Mul_bool:
goto start;

_Sub_int:
Sub_int(memoryStack);
goto start;

_Sub_float:
Sub_float(memoryStack);
goto start;

_Sub_bool:
goto start;

_Div_int:
Div_int(operationStack);
goto start;

_Div_float:
Div_float(operationStack);
goto start;

_Div_bool:
goto start;

_Not_int:
goto start;

_Not_float:
goto start;

_Not_bool:
Not_bool(operationStack);
goto start;

_And_int:
goto start;

_And_float:
goto start;

_And_bool:
And_bool(operationStack);
goto start;

_Or_int:
goto start;

_Or_float:
goto start;

_Or_bool:
Or_bool(operationStack);
goto start;

_Set_int:
Set_int(&current,operationStack,memoryStack,bytecode);
goto start;

_Set_float:
goto start;

_Set_bool:
goto start;

_Call_int:
Call_int(operationStack);
goto start;

_Call_float:
goto start;

_Call_bool:
goto start;

_CallNative_int:
goto start;

_CallNative_float:
goto start;

_CallNative_bool:
goto start;

_Comp_int:
Comp_int(operationStack, &cmpFlag);
goto start;

_Comp_float:
goto start;

_Comp_bool:
goto start;

_CmpG_int:
CmpG_int(operationStack);
goto start;

_CmpG_float:
CmpG_float(operationStack);
goto start;

_CmpG_bool:
CmpG_bool(operationStack);
goto start;

_CmpGEq_int:
CmpGEq_int(operationStack);
goto start;

_CmpGEq_float:
CmpGEq_float(operationStack);
goto start;

_CmpGEq_bool:
CmpGEq_bool(operationStack);
goto start;

_CmpL_int:
CmpL_int(operationStack);
goto start;

_CmpL_float:
CmpL_float(operationStack);
goto start;

_CmpL_bool:
CmpL_bool(operationStack);
goto start;

_CmpLEq_int:
CmpLEq_int(operationStack);
goto start;

_CmpLEq_float:
CmpLEq_float(operationStack);
goto start;

_CmpLEq_bool:
CmpLEq_bool(operationStack);
goto start;

_CmpEq_int:
CmpEq_int(operationStack);
goto start;

_CmpEq_float:
CmpEq_float(operationStack);
goto start;

_CmpEq_bool:
CmpEq_bool(operationStack);
goto start;

_CmpNEq_int:
CmpNEq_int(operationStack);
goto start;

_CmpNEq_float:
CmpNEq_float(operationStack);
goto start;

_CmpNEq_bool:
CmpNEq_bool(operationStack);
goto start;

_Push_int:
Push_int(&current,operationStack,bytecode);
goto start;

_Push_float:
Push_float(&current,operationStack,bytecode);
goto start;

_Push_bool:
Push_bool(&current,operationStack,bytecode);
goto start;

_Load_int:
Load_int(&current,operationStack,memoryStack,bytecode);
goto start;

_Load_float:
Load_float(&current,operationStack,memoryStack,bytecode);
goto start;

_Load_bool:
Load_bool(&current,operationStack,memoryStack,bytecode);
goto start;

_Jmp_int:
Jmp_int(&current, bytecode);
goto start;

_Jmp_float:
goto start;

_Jmp_bool:
goto start;

_JmpTrue_int:
JmpTrue_int(&current,operationStack);
goto start;

_JmpTrue_float:
goto start;

_JmpTrue_bool:
goto start;

_JmpFalse_int:
JmpFalse_int(&current,operationStack);
goto start;

_JmpFalse_float:
goto start;

_JmpFalse_bool:
goto start;


}
