

###
 Compare operators should do their logic on the top 2 values of stack
 push 1 if true, 0 if false
 cmp pushes 0, compares with vlaue.
 JumpG and jump are the only jumps we need.
###

int:count = 1

int:one = 0
int:two = 1


while(count<=(count*count/count - (0-0+1-1+count) + 1)) 
{
    
    count = count + 1

    int:temp = one

    one = two
    two = two + temp
    
}

if(two < -2)
{
    print(67)
}


print(two)

